ecommerce/config/routes.rb
Rails.application.routes.draw do
  resources :cars do
    resources :questions
  end
  
  devise_for :users
  resources :users
  
  root to: "home#index"
  
  get "about", to: "about#index", as: :about
  get "contact", to: "contact#index", as: :contact

  get "active_posts", to: "users#active_posts"
  get "purchase_history", to: "users#purchase_history"
  get "sale_history", to: "users#sale_history"

  get "cars/buy/:car_id", to: "cars#buy", as: :buy
  get "cars/buy/confirm_purchase/:car_id", to: "cars#confirm_purchase", as: :confirm_purchase

  get "cars/sort_by_setting/:setting_id", to: "cars#change_sort_by_setting", as: :change_sort_by_setting

  #no tocar
  get "cars/:car_id/questions/:id/answer", to: "questions#answer", as: :answer
  post "cars/:car_id/questions/:id/answer", to: "questions#answer"
  patch "cars/:car_id/questions/:id/answer", to: "questions#update"

end

ecommerce/app/models/question.rb
class Question < ApplicationRecord
    validates :car_id, :user_id, :presence => true
    has_rich_text :content
    has_rich_text :answer
    belongs_to :car
    belongs_to :user
end

ecommerce/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy answer ]
  before_action :set_car, except: %i[ index answer ]
  before_action :correct_user, only: [:answer]
  before_action :authenticate_user!, only: [:new]

  # GET /questions or /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = @car.questions.new
  end

  # GET /questions/1/edit
  def edit
    @car = @question.car
  end

  # POST /questions or /questions.json
  def create
    @question = @car.questions.new(question_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @question.save
        format.html { redirect_to car_path(@car), notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    @question.update(question_params)
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to car_path(@car), notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    if @question.destroy
      flash[:notice] = "Question was successfully destroyed."
      redirect_to car_path(@car)
    end
  end

  def correct_user
    current_car = current_user.cars.find_by(id: @question.car_id)
    redirect_to cars_path, notice: "Not autorithized to answer this question." if current_car.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    def set_car
      @car = Car.find(params[:car_id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      if params.require(:question).permit(:answer)
        params.require(:question).permit(:title, :content, :answer)
      else 
        params.require(:question).permit(:title, :content)
      end
    end
end

ecommerce/app/helpers/questions_helper.rb
module QuestionsHelper
end

ecommerce/app/views/questions/_answer_form.html.erb
<%= form_with(model: @question, url: answer_path(@car.id, @question.id)) do |form| %>
    <% if @question.errors.any? %>
      <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
      <% @question.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
      </ul>
      </div>
    <% end %>
    
    <%= form.hidden_field :title, value: @question.title %>
    <%= form.hidden_field :content, value: @question.content %>
    <%= form.hidden_field :user_id, value: @question.user_id %>
    
    <div class="field text-dark">
        <br><%= form.label "ANSWER", class:"col-form-label" %> <i class="text-muted">(write your answer here)</i><br>
        <%= form.rich_text_area :answer, class:"form-control field question-form--text-area", required: true %>
    </div><br>

    <div class="actions form-group text-end">
        <%= link_to image_tag("Icons/back_icon_black.png", class:"question--back-btn-image"), car_path(@car), class:"btn btn-warning btn-lg answer-form--btn answer-form--back-btn", title:"Go back" %> &nbsp &nbsp
        <%= form.submit "Send answer", class:"btn btn-primary btn-lg answer-form--btn"%>
        <br><br>
    </div>

<% end %>

ecommerce/app/views/questions/_form.html.erb
<div class="card-body">
  <%= form_with(model: [@car, @question]) do |form| %>
    <% if question.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

        <ul>
          <% question.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form-group col-10 mx-auto">
      <%= form.label "TOPIC", class:"col-form-label" %><br>
      <%= form.text_field :title, class:"form-control form-control-lg field", required: true %>
    </div>

    <div class="field form-group col-10 mx-auto">
      <%= form.label "QUESTION", class:"col-form-label" %><br>
      <%= form.rich_text_area :content, class:"form-control field question-form--text-area", required: true %>
    </div>

    <%= form.hidden_field :user_id, value: current_user.id %>

    &nbsp <br>

    <div class="actions form-group text-end questions-form--submit-div">
      <%= form.submit "Post Question", class:"btn btn-primary btn-lg question-form--btn"%> &nbsp &nbsp
      <%= link_to 'Back', car_path(params[:car_id]), class:"btn btn-warning btn-lg question-form--btn" %>
    </div>
      
  <% end %>
</div>

ecommerce/app/views/questions/answer.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @question.user.username %>
</p>

<%if @question.answer%>
  <p>
    <strong>Answer:</strong>
    <%= @question.answer %>
  </p>
<%end%>

<br><br>
    <% if user_signed_in? and @car.user_id == current_user.id %>
    <%= form_with(model: @question, url: answer_path(@car.id, @question.id)) do |form| %>
      <% if @question.errors.any? %>
      <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
        <ul>
          <% @question.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
        </ul>
      </div>
    <% end %>
      
      <%= form.hidden_field :title, value: @question.title %>
      <%= form.hidden_field :content, value: @question.content %>
      <%= form.hidden_field :user_id, value: @question.user_id %>
      
      <div class="field">
      <%= form.label "answer" %>
        <%= form.text_field :answer %>
        </div>
    
        <div class="actions">
        <%= form.submit "Send answer", class:"btn btn-dark" %>
        </div>
        
      <% end %>
    <% end %>
<br>  

<%= link_to 'Edit', edit_car_question_path(@car, @question) %> |
<%= link_to 'Back', car_path(@car) %>

ecommerce/app/views/questions/edit.html.erb
<div class="card question-form--card-div">
    <h2 class="card-header text-dark border-0">Edit your question</h2>
    <h6 class="card-header text-dark small text-muted">Edit the question you asked by filling this form</h6>
    <%= render 'form', question: @question %>
</div>

ecommerce/app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= question.content %></td>
        <td><%= question.user.username %></td>
        <td><%= link_to 'Show', car_question_path(question.car, question) %></td>
        <td><%= link_to 'Edit', edit_car_question_path(question.car, question) %></td>
        <td><%= link_to 'Destroy', car_question_path(question.car, question), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_car_question_path %>

ecommerce/app/views/questions/new.html.erb
<div class="card question-form--card-div">
    <h2 class="card-header text-dark border-0">Ask a question</h2>
    <h6 class="card-header text-dark small text-muted">Ask anything about the product you would to know by filling this form</h6>
    <%= render 'form', question: @question %>
</div>

ecommerce/app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card question-show--card-div">
  <h2 class="card-header text-dark text-center border-0">Topic: "<%=@question.title %>"</h2>
  <h3 class="card-header small text-dark text-muted text-center">Question from <i><%=@question.user.username%></i></h3>
  
  <div class="container text-dark col-10 mx-auto">
    <br>
    <div class="field text-dark">
        <label class="col-form-label">QUESTION</label>
    </div>
    <div class="field text-dark form-control question-show--question-content-div">
        <%= @question.content %>
    </div>
  </div>

  <div class="container text-dark col-10 mx-auto">
    <% if is_user_signed_in_car_owner(@car) %>
      <%= render 'answer_form', question: @question %>
    <% end %>
  </div>

</div><br>