ecommerce/config/routes.rb
Rails.application.routes.draw do
  resources :cars do
    resources :questions
  end
  
  devise_for :users
  resources :users
  
  root to: "home#index"
  
  get "about", to: "about#index", as: :about
  get "contact", to: "contact#index", as: :contact

  get "active_posts", to: "users#active_posts"
  get "purchase_history", to: "users#purchase_history"
  get "sale_history", to: "users#sale_history"

  get "cars/buy/:car_id", to: "cars#buy", as: :buy
  get "cars/buy/confirm_purchase/:car_id", to: "cars#confirm_purchase", as: :confirm_purchase

  get "cars/sort_by_setting/:setting_id", to: "cars#change_sort_by_setting", as: :change_sort_by_setting

  #no tocar
  get "cars/:car_id/questions/:id/answer", to: "questions#answer", as: :answer
  post "cars/:car_id/questions/:id/answer", to: "questions#answer"
  patch "cars/:car_id/questions/:id/answer", to: "questions#update"

end

ecommerce/app/models/car.rb
require "open_exchange_rates"

class Car < ApplicationRecord
    has_one_attached :car_image
    belongs_to :user, optional: true
    has_many :questions

    def exchange_price(currency)
        exchange = OpenExchangeRates::Rates.new(:app_id => "d048914d53b24d148811eb19ebaa047b")
        return exchange.convert(self.price, :from => "USD", :to => currency)
    end

    def image_path()
        model = self.car_model.downcase
        model_aux = model.gsub(" ", "-").delete("/")
        path_for_html = self.car_class+"/"+model_aux+".png"
        path = "./app/assets/images/"+path_for_html
        if File.exist?(path)
            return path, path_for_html
        end
        return nil, nil
    end
end

ecommerce/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  before_action :sort_by_init
  helper_method :sort_by_get_helper, :sort_by_price_helper, :sort_by_car_model_helper, :sort_by_manufacturer_helper,
                :sort_by_order_asc_helper, :sort_by_order_desc_helper
  
  

  # GET /cars or /cars.json
  def index

    @cars = Car.all.where(is_for_sale: true).order(session[:sort_by_setting].to_sym => session[:sort_by_order].to_sym)


    @array_four_cars = []
    arrange_cars_in_four_cars(@cars, @array_four_cars)
    
    @last_index = @array_four_cars.size
    @last_index -= 1
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    #@car = Car.new
    @car = current_user.cars.build
  end

  # GET /cars/1/edit
  def edit
  end

  def buy
    car_id = buy_path().gsub( buy_path().tr("0-9","") , "").to_i
    @car = Car.find_by_id(car_id)
  end

  def confirm_purchase
    car_id = confirm_purchase_path().gsub( confirm_purchase_path().tr("0-9","") , "").to_i
    @car = Car.find_by_id(car_id)

    @car.update(is_for_sale: false)
    @car.update(buyer_id: current_user.id)
    @car.update(purchased_at: Time.current)

    redirect_to cars_path(), notice: "Car was successfully purchased."
  end

  # POST /cars or /cars.json
  def create
    #@car = Car.new(car_params)
    @car = current_user.cars.build(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to active_posts_path, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @car = current_user.cars.find_by(id: params[:id])
    redirect_to cars_path, notice: "Not autorithized to edit this car." if @car.nil?
  end

  def change_sort_by_setting
    setting_id = change_sort_by_setting_path().gsub( change_sort_by_setting_path().tr("0-9","") , "").to_i

    if setting_id == 1
      sort_by_car_model_helper()
      sort_by_order_asc_helper()
    elsif setting_id == 2
      sort_by_car_model_helper()
      sort_by_order_desc_helper()
    elsif setting_id == 3
      sort_by_manufacturer_helper()
      sort_by_order_asc_helper()
    elsif setting_id == 4
      sort_by_manufacturer_helper()
      sort_by_order_desc_helper()
    elsif setting_id == 5
      sort_by_price_helper()
      sort_by_order_desc_helper()
    else
      sort_by_price_helper()
      sort_by_order_asc_helper()
    end

    redirect_to cars_path
  end
  
  private

  
  # Use callbacks to share common setup or constraints between actions.
  def set_car
    @car = Car.find(params[:id])
  end
  
  #Por default va a ordenar por car_model
    def sort_by_init
      if session[:sort_by_setting].nil? || session[:sort_by_order].nil?
        session[:sort_by_setting] = "car_model"
        session[:sort_by_order] = "asc"
      end
    end
  
    def sort_by_get_helper
      session[:sort_by_setting]
    end
  
    def sort_by_price_helper
      session[:sort_by_setting] = "price"
    end

    def sort_by_car_model_helper
      session[:sort_by_setting] = "car_model"
    end

    def sort_by_manufacturer_helper
      session[:sort_by_setting] = "manufacturer"
    end

    def sort_by_order_asc_helper
      session[:sort_by_order] = "asc"
    end

    def sort_by_order_desc_helper
      session[:sort_by_order] = "desc"
    end

    def sort_by_current_setting(cars)
      cars.order(session[:sort_by_setting].to_sym => :desc)
    end

    def arrange_cars_in_four_cars(cars, array_four_cars)
      i = 0
      four_cars = []
  
      cars.each do |car|
        four_cars.push(car)
        i+=1
        if i == 4
            array_four_cars.push(four_cars)
            four_cars = []
            
            i = 0
        end
      end
      
      if i != 0
        array_four_cars.push(four_cars)
        four_cars = []
      end
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:car_image, :car_model, :car_class, :car_type, :body, :capacity, :manufacturer, :price, :user_id, :is_for_sale, :buyer_id, :purchased_at)
    end
end

ecommerce/app/helpers/cars_helper.rb
module CarsHelper

    def is_user_signed_in_car_owner(car)
        return user_signed_in? && (car.user_id == current_user.id)
    end

    def is_user_signed_in_the_question_owner(question)
        return user_signed_in? && (question.user_id == current_user.id)
    end

    def is_user_signed_in_car_owner_and_able_to_answer(question)
        return user_signed_in? && @car.user_id == current_user.id && question.answer.nil?
    end

    def is_user_signed_in_car_owner_and_already_answered(question)
        return user_signed_in? && @car.user_id == current_user.id && !question.answer.nil?
    end

    def question_is_answered(question)
        !question.answer.nil?
    end
    
end

ecommerce/app/views/cars/_car_catalogue.html.erb
<div class="container">
  <div class="row row-cols-4">

    <% cars.each do |car| %>

      <% unless car.nil? %>

        <div class="col">
        <% if car.car_image.attached? %>
          <%= link_to image_tag(url_for(car.car_image), class:"img-fluid car-catalogue--car-image"), car_path(id: car.id), title: "Click for more info" %>
        <%end%>
          <h6 class="text-white text-uppercase d-block small text-center car-catalogue--header"> <%= car.manufacturer %> </h6>
          <h4 class="text-white text-uppercase text-center"> <%= link_to car.car_model, car_path(id: car.id), class:"catalogue--car-model-link", title: "Click for more info" %> </h4>
          <h5 class="text-white text-uppercase text-center car-catalogue--header"><%= "$" + number_with_delimiter( car.price, delimiter:".").to_s %></h5>
          
          <% if is_user_signed_in_car_owner(car) %>
            <%= link_to image_tag("Icons/shopping_cart_white.png", class:"buy-btn--image") + "BUY", "", class:"btn btn-success btn-buy btn-buy-disabled d-block", data: { confirm: "You cannot buy from your own post." }, title: "You cannot buy from your own post" %>
          <% else %>
            <%= link_to image_tag("Icons/shopping_cart_white.png", class:"buy-btn--image") + "BUY", buy_path(car.id), class:"btn btn-success btn-buy d-block", title: "Go to purchase confirmation" %>
          <% end %>
        </div>

      <% else %>
        <div class="col"></div>
      <% end %>

    <% end %>

  </div>
</div>
<br/>

ecommerce/app/views/cars/_car_details.html.erb
<div class="card-body">
    
    <div class="d-inline-block show--div-info">

    <div class="row">
        <div class="col-4 text-center">
          <image src="<%= (url_for(@car.car_image)) %>" class="img-fluid show--car-image">
        </div>
        <div class="col col-form-label">
            <table class="table car-show--table">
            <tr>
            <td><div class="field form-group"><label class="small"><p class="car-show--table-labels d-inline">Manufacturer</p></label></div></td>
                    <td><%= @car.manufacturer %></td>
                    </tr>
                <tr>
                    <td><div class="field form-group"><label class="small"><p class="car-show--table-labels d-inline">Capacity</p></label></div></td>
                    <td><%= @car.capacity %></td>
                    </tr>
                <tr>
                    <td><div class="field form-group"><label class="small"><p class="car-show--table-labels d-inline">Car class</p></label></div></td>
                    <td><%= @car.car_class %></td>
                </tr>
                <tr>
                <td><div class="field form-group"><label class="small"><p class="car-show--table-labels d-inline">Car type</p></label></div></td>
                <td><%= @car.car_type %></td>
                </tr>
                <tr>
                <td><div class="field form-group"><label class="small"><p class="car-show--table-labels d-inline">Body car type</p></label></div></td>
                <td><%= @car.body %></td>
                </tr>
                <% if false %>
                    <tr>
                        <td><div class="field form-group"><label class="small"><p class="car-show--table-labels d-inline">Price</p></label></div></td>
                        <td><%= "USD " + number_with_delimiter( @car.price, delimiter:".").to_s %><br>
                        <%= " EUR " + number_with_delimiter( @car.exchange_price('EUR'), delimiter:".").to_s %><br> 
                        <%= " ARS " + number_with_delimiter( @car.exchange_price('ARS'), delimiter:".").to_s %><br>
                        <%= " BRL " + number_with_delimiter( @car.exchange_price('BRL'), delimiter:".").to_s %></td>
                    </tr>   
                <% end %>
                <% if is_user_signed_in_car_owner(@car) && @car.is_for_sale %>
                <tr class="borderless-cell text-end">
                        <td></td>
                        <td>                            
                            <div class="d-inline-block text-center">
                                <div class="d-inline"><%= link_to image_tag("Icons/edit_page_black.png", class:"car-show--edit-image") + "EDIT", edit_car_path(@car), class:"btn btn-warning car-show--details-btn" %></div><br>
                                <p class="d-inline car-show--table-edit-btn">This is your post, edit it here.</p>
                            </div>
                        </td>
                    </tr>
                <% elsif @car.is_for_sale %>
                    <tr class="borderless-cell text-end">
                        <td></td>
                        <td>
                            <div class="d-inline-block text-center">
                                <div class="d-inline-block text-center">
                                    <div class="d-inline"><%= link_to image_tag("Icons/shopping_cart_white.png", class:"buy-btn--image") + "BUY", buy_path(@car.id), class:"btn btn-success btn-buy car-show--btn-buy", title: "Go to purchase confirmation" %></div><br>
                                    <p class="d-inline car-show--table-edit-btn">&nbsp</p>
                                </div>
                                <div class="d-inline-block text-center">
                                    <div class="d-inline"><%= link_to image_tag("Icons/question_bubble_white.png", class:"car-show--question-image") + "Ask the seller", new_car_question_path(@car), class: "btn btn-primary car-show--details-btn" %></div><br>
                                    <p class="d-inline car-show--table-edit-btn">Any doubts?</p>
                                </div>
                            </div>
                        </td>
                    </tr>
                <% end %>
            </table>
        </div>
	</div>
    </div>
  </div>

ecommerce/app/views/cars/_car_questions.html.erb
<div>
    <br>
    <h2 class="card-header text-light text-center border-0"><%= "Questions" %></h2>

    <tbody>
      <% @car.questions.each do |question| %>
        <br>
        <div class="card text-white bg-secondary car-show-details--question-card">
            <div class="card-header">
                <div>
                    <h3 class="text-start d-inline">
                        <div class="field form-group d-inline">
                            <label><p class="car-show--table-labels d-inline">Topic:</p></label>
                        </div>
                        <%= question.title %>
                    </h3>
                    <% if is_user_signed_in_the_question_owner(question) && @car.is_for_sale %>
                        <% if !question_is_answered(question) %>
                            <div class="d-inline text-end car-show--question-btns-div">
                                <%= link_to image_tag("Icons/pencil_white.png", class:"car-show--edit-question-btn"), edit_car_question_path(question.car, question), title:"Edit question" %> &nbsp &nbsp
                                <%= link_to image_tag("Icons/trash_icon_white.png", class:"car-show--edit-question-btn"), car_question_path(question.car, question), method: :delete, data: { confirm: 'Are you sure?' }, title:"Delete question" %>
                            </div>
                        <% else %>
                            <div class="d-inline text-end car-show--question-btns-div">
                                <%= link_to image_tag("Icons/trash_icon_white.png", class:"car-show--edit-question-btn"), car_question_path(question.car, question), method: :delete, data: { confirm: 'Are you sure?' }, title:"Delete question" %>
                            </div>
                        <% end %>
                    <% elsif is_user_signed_in_car_owner_and_able_to_answer(question) && @car.is_for_sale %>
                        <div class="d-inline text-end car-show--question-btns-div">
                            <%= link_to image_tag("Icons/message_icon_black", class:"car-show--answer-question-image") + "Answer", car_question_path(@car, question), class:"btn btn-light car-show--answer-question-btn small", title:"Answer question" %> &nbsp &nbsp 
                            <%= link_to image_tag("Icons/trash_icon_white.png", class:"car-show--edit-question-btn"), car_question_path(question.car, question), method: :delete, data: { confirm: 'Are you sure?' }, title:"Delete question" %>
                        </div>
                    <% elsif is_user_signed_in_car_owner_and_already_answered(question) && @car.is_for_sale %>
                        <div class="d-inline text-end car-show--question-btns-div">
                            <%= link_to image_tag("Icons/trash_icon_white.png", class:"car-show--edit-question-btn"), car_question_path(question.car, question), method: :delete, data: { confirm: 'Are you sure?' }, title:"Delete question" %>
                        </div>
                    <% end %>
                </div>
            </div>

            <div class="container">
                <p><%= question.content %></p>
                <h6 class="text-light text-end small car-show--question-user-h6"><i>Asked by <%= question.user.username %>, <%= question.created_at.strftime("%d/%m/%Y") %></i></h6>
            </div>
        </div>

        <% if question_is_answered(question) %>
            <div class="card text-white car-show-details--answer-card">
                <div class="card-header">
                    <h3 class="text-start d-inline">
                        <div class="field form-group d-inline">
                            <label><p class="car-show--table-labels d-inline">Answer:</p></label>
                        </div>
                    </h3>
                
                    <% if is_user_signed_in_car_owner_and_already_answered(question) && @car.is_for_sale %>
                        <div class="d-inline text-end car-show--question-btns-div">
                            <%= link_to image_tag("Icons/pencil_white.png", class:"car-show--edit-question-btn"), car_question_path(@car, question), title:"Edit answer" %>
                        </div>
                    <% end %>
                </div>
               
                <div class="container">
                    <p><%= question.answer %></p>
                    <h6 class="text-light text-end small car-show--question-user-h6"><i>Answered by <%= @car.user.username %> </i></h6>
                </div>
            </div>
            <br>
        <% else %>
            <br><br>
        <% end %> 
    <% end %>

    <% if @car.questions.count == 0 %>
        <br>
        <p class="text-center lead">No one has asked anything in this post yet. Be the first one!</p>
        <br><br>
    <% end %>

    </tbody>
</div>

ecommerce/app/views/cars/_form.html.erb
<div class="card-body">
  <%= form_with(model: car) do |form| %>
    <% if car.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

        <ul>
          <% car.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form-group col-10 mx-auto">
      <%= form.label "Car image", class:"col-form-label" %>
      <%= form.file_field :car_image, required: true %>
    </div>

    <div class="field form-group col-10 mx-auto">
      <%= form.label :car_model, class:"col-form-label" %>
      <%= form.text_field :car_model, class:"form-control form-control-lg field", maxlength:"17", required: true %>
    </div>

    <div class="field form-group col-10 mx-auto">
      <%= form.label :car_class, class:"col-form-label" %>
      <%= form.text_field :car_class, class:"form-control form-control-lg field", maxlength:"45", required: true %>
    </div>

    <div class="field form-group col-10 mx-auto">
      <%= form.label :car_type, class:"col-form-label" %>
      <%= form.text_field :car_type, class:"form-control form-control-lg field", maxlength:"45", required: true %>
    </div>

    <div class="field form-group col-10 mx-auto">
      <%= form.label :body, class:"col-form-label" %>
      <%= form.text_field :body, class:"form-control form-control-lg field", maxlength:"45", required: true %>
    </div>

    <div class="field form-group col-10 mx-auto">
      <%= form.label :capacity, class:"col-form-label" %>
      <%= form.text_field :capacity, class:"form-control form-control-lg field", maxlength:"45", required: true %>
    </div>

    <div class="field form-group col-10 mx-auto">
      <%= form.label :manufacturer, class:"col-form-label" %>
      <%= form.text_field :manufacturer, class:"form-control form-control-lg field", maxlength:"20", required: true %>
    </div>

    <div class="field form-group col-10 mx-auto">
      <%= form.label :price, class:"col-form-label" %>
      <%= form.number_field :price, required: true, min:"0", max:(2**63).to_s %>
    </div>
    
    <div class="field form-group">
        <%= form.number_field :user_id, id: :car_user_id, value: current_user.id, type: :hidden %> 
    </div>

    <div class="field form-group">
        <%= form.number_field :is_for_sale, value: "1", type: :hidden %> 
    </div>

    <br>

    <div class="actions form-group text-center">
      <%= form.submit class: "btn btn-success btn-lg car-form--btn-submit", value:"Post car for sale", data: { disable_with: "Post car for sale" } %>
    </div>
  <% end %>
</div>

ecommerce/app/views/cars/buy.html.erb
<div class="card question-show--card-div">
    
    <h2 class="card-header text-center">
        <div class="field form-group">
            <label><p class="d-inline"><%= @car.car_model %></p></label>
        </div>
    </h2>
    
    <div class="card-body">

        <div class="row">
            <div class="col-4 text-center">
                <image src="<%= (url_for(@car.car_image)) %>" class="img-fluid buy--car-image">
            </div>
            <div class="col col-form-label">
                <table class="table">
                    <tr>
                        <td><div class="field form-group"><label class="small"><p class="d-inline">Price</p></label></div></td>
                        <td><%= "$" + number_with_delimiter( @car.price, delimiter:".").to_s %></td>
                    </tr>
                    <tr>
                        <td><div class="field form-group"><label class="small"><p class="d-inline">Manufacturer</p></label></div></td>
                        <td><%= @car.manufacturer %></td>
                    </tr>
                    <tr>
                        <td><div class="field form-group"><label class="small"><p class="d-inline">Capacity</p></label></div></td>
                        <td><%= @car.capacity %></td>
                    </tr>
                    <tr>
                        <td><div class="field form-group"><label class="small"><p class="d-inline">Car class</p></label></div></td>
                        <td><%= @car.car_class %></td>
                    </tr>
                    <tr>
                        <td><div class="field form-group"><label class="small"><p class="d-inline">Car type</p></label></div></td>
                        <td><%= @car.car_type %></td>
                    </tr>
                    <tr>
                        <td><div class="field form-group"><label class="small"><p class="d-inline">Body car type</p></label></div></td>
                        <td><%= @car.body %></td>
                    </tr>
                    <tr class="borderless-cell text-end">
                        <td></td>
                        <td>
                            <div class="d-inline-block text-center">
                                <%if false%>
                                
                                <%= form_with(model: @car) do |form| %>

                                <% if @car.errors.any? %>
                                    <div id="error_explanation">
                                        <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

                                        <ul>
                                        <% @car.errors.each do |error| %>
                                            <li><%= error.full_message %></li>
                                        <% end %>
                                        </ul>
                                    </div>
                                <% end %>

                                <%= form.number_field :is_for_sale, value: "0", type: :hidden %> 
                                <%= form.number_field :buyer_id, value: current_user.id, type: :hidden %> 
                                <%= form.date_field :purchased_at, value: Time.current, type: :hidden %> 

                                <div class="d-inline">
                                <%= form.submit class: "btn btn-success btn-buy", value:"CONFIRM PURCHASE", data: { disable_with: "CONFIRM PURCHASE" } %>
                                </div><br>

                                <% end %>
                                <% end %>
                                <div class="d-inline"><%= link_to image_tag("Icons/shopping_cart_white.png", class:"buy-btn--image") + "CONFIRM PURCHASE", confirm_purchase_path(@car.id), class:"btn btn-success btn-buy", title: "Confirm purchase and buy this car" %></div><br>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>

ecommerce/app/views/cars/edit.html.erb
<div class="card col-6 mx-auto car-form--card-div">
    <h2 class="card-header text-dark border-0">Edit Car Form</h2>
    <h6 class="card-header text-dark small text-muted">Edit your car post by modifying the next form</h6>
    <%= render 'form', car: @car %>
</div>

ecommerce/app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container mx-auto cars--index--catalogue-container">
  <br>
  <h1 class="text-center">Catalogue</h1>
  <p class="text-center lead"><small>Happy shopping!</small></p>
    <a class="dropdown-toggle btn btn-light car-show--sort-by-btn" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Sort by</a>
    <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDarkDropdownMenuLink">
      <li><%= link_to "Car model (A-Z)", change_sort_by_setting_path(1), class:"dropdown-item" %></li>
      <li><%= link_to "Car model (Z-A)", change_sort_by_setting_path(2), class:"dropdown-item" %></li>
      <li><%= link_to "Manufacturer (A-Z)", change_sort_by_setting_path(3), class:"dropdown-item" %></li>
      <li><%= link_to "Manufacturer (Z-A)", change_sort_by_setting_path(4), class:"dropdown-item" %></li>
      <li><%= link_to "Price (High-Low)", change_sort_by_setting_path(5), class:"dropdown-item" %></li>
      <li><%= link_to "Price (Low-High)", change_sort_by_setting_path(6), class:"dropdown-item" %></li>
    </ul>

  <br><br><br>

  <% unless @array_four_cars.size == 0 %>
    <% @array_four_cars.each_with_index do |four_cars, j| %>
      
      <%= render partial: 'car_catalogue', locals: {cars: four_cars} %>

      <% if j != @last_index %>
        <br><br><br>
      <% else %>
        <br>
      <% end %>
    <% end %>

  <% else %>
    <p class="text-center lead">We are sorry, but currently there are no cars on sale.</p>
    <br><br>
  <% end %>
</div>

<br><br>

ecommerce/app/views/cars/new.html.erb
<div class="card col-6 mx-auto car-form--card-div">
    <h2 class="card-header text-dark border-0">Car Sale Form</h2>
    <h6 class="card-header text-dark small text-muted">Add your car for sale by filling the next form</h6>
    <%= render 'form', car: @car %>
</div>

<br><br>

ecommerce/app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card mx-auto text-light show--card">
  
  <h2 class="card-header text-center">
    <div class="field form-group">
        <label><p class="show--car-head d-inline"><%= @car.car_model %></p></label>
    </div>
  </h2>
  
  <%= render "car_details" %>

  <hr class="car-show--card-divider">

  <%= render "car_questions" %>
</div>
<br>