ecommerce/config/routes.rb
Rails.application.routes.draw do
  resources :cars do
    resources :questions
  end
  
  devise_for :users
  resources :users
  
  root to: "home#index"
  
  get "about", to: "about#index", as: :about
  get "contact", to: "contact#index", as: :contact

  get "active_posts", to: "users#active_posts"
  get "purchase_history", to: "users#purchase_history"
  get "sale_history", to: "users#sale_history"

  get "cars/buy/:car_id", to: "cars#buy", as: :buy
  get "cars/buy/confirm_purchase/:car_id", to: "cars#confirm_purchase", as: :confirm_purchase

  get "cars/sort_by_setting/:setting_id", to: "cars#change_sort_by_setting", as: :change_sort_by_setting

  #no tocar
  get "cars/:car_id/questions/:id/answer", to: "questions#answer", as: :answer
  post "cars/:car_id/questions/:id/answer", to: "questions#answer"
  patch "cars/:car_id/questions/:id/answer", to: "questions#update"

end

ecommerce/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

ecommerce/app/helpers/home_helper.rb
module HomeHelper
end

ecommerce/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"><%= link_to image_tag("legendary_motorsport_logo_white.png", class:"header--lm-logo"), root_path, class:"navbar-brand" %></li>
        <li class="nav-item"><%= link_to "Catalogue", cars_path, class:"nav-link header--nav-item" %></li>
        <li class="nav-item"><%= link_to "Contact", contact_path, class:"nav-link header--nav-item" %></li>
        <li class="nav-item"><%= link_to "About us", about_path, class:"nav-link header--nav-item" %></li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "Sell", new_car_path, class:"nav-link header--nav-item" %></li>
      </ul>
      <ul class="navbar-nav" aria-labelledby="navbarDarkDropdownMenuLink">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle header--nav-item" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Account</a>
          <ul class="dropdown-menu dropdown-menu-lg-end header--dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
            <% if user_signed_in? %>
              <li> <%= link_to current_user.username, "#", class:"dropdown-item disabled text-center header--username-item" %> </li>
              <li><%= link_to "Purchase history", purchase_history_path, class:"dropdown-item" %></li>
              <li><%= link_to "Sale history", sale_history_path, class:"dropdown-item" %></li>
              <li><%= link_to "Active posts", active_posts_path, class:"dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Profile", current_user, class:"dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"dropdown-item" %></li>
            <% else %>
              <li><%= link_to "Sign in", new_user_session_path, class:"dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Sign up", new_user_registration_path, class:"dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
      </ul>

    </div>
  </div>
</nav>

ecommerce/app/views/home/index.html.erb
<div class="container center-block">
    
    <div class="text-center">
        <%= image_tag "legendary_motorsport_logo.png", alt:"Legendary Motorsport logo" %>
    </div>
    
    <br><br>
    
    <h4 class="text-justify">Are you looking for a safe, eco-friendly, fuel efficient car that's practical for getting around town? Well you are in the wrong website. Are you looking to get them open-mouthed as you pass by? Welcome! You are in a safe place.</h4>

    <h4>Do you want to buy some badass looking cars? <%= link_to "Click here", cars_path, class:"home--link" %>.</h4>
</div>